function countryFlag(iso2) {
  return String.fromCodePoint(
    ...[...iso2.toUpperCase()].map((c) => 0x1f1e6 - 65 + c.charCodeAt(0))
  );
}

var countries = [
  { name: "Afghanistan", nameId: "Afganistan", iso2: "AF", dialCode: "93" },
  { name: "Albania", nameId: "Albania", iso2: "AL", dialCode: "355" },
  { name: "Algeria", nameId: "Aljazair", iso2: "DZ", dialCode: "213" },
  { name: "American Samoa", nameId: "Samoa Amerika", iso2: "AS", dialCode: "1684" },
  { name: "Andorra", nameId: "Andorra", iso2: "AD", dialCode: "376" },
  { name: "Angola", nameId: "Angola", iso2: "AO", dialCode: "244" },
  { name: "Anguilla", nameId: "Anguilla", iso2: "AI", dialCode: "1264" },
  { name: "Antigua and Barbuda", nameId: "Antigua dan Barbuda", iso2: "AG", dialCode: "1268" },
  { name: "Argentina", nameId: "Argentina", iso2: "AR", dialCode: "54" },
  { name: "Armenia", nameId: "Armenia", iso2: "AM", dialCode: "374" },
  { name: "Aruba", nameId: "Aruba", iso2: "AW", dialCode: "297" },
  { name: "Australia", nameId: "Australia", iso2: "AU", dialCode: "61" },
  { name: "Austria", nameId: "Austria", iso2: "AT", dialCode: "43" },
  { name: "Azerbaijan", nameId: "Azerbaijan", iso2: "AZ", dialCode: "994" },
  { name: "Bahamas", nameId: "Bahama", iso2: "BS", dialCode: "1242" },
  { name: "Bahrain", nameId: "Bahrain", iso2: "BH", dialCode: "973" },
  { name: "Bangladesh", nameId: "Bangladesh", iso2: "BD", dialCode: "880" },
  { name: "Barbados", nameId: "Barbados", iso2: "BB", dialCode: "1246" },
  { name: "Belarus", nameId: "Belarus", iso2: "BY", dialCode: "375" },
  { name: "Belgium", nameId: "Belgia", iso2: "BE", dialCode: "32" },
  { name: "Belize", nameId: "Belize", iso2: "BZ", dialCode: "501" },
  { name: "Benin", nameId: "Benin", iso2: "BJ", dialCode: "229" },
  { name: "Bermuda", nameId: "Bermuda", iso2: "BM", dialCode: "1441" },
  { name: "Bhutan", nameId: "Bhutan", iso2: "BT", dialCode: "975" },
  { name: "Bolivia", nameId: "Bolivia", iso2: "BO", dialCode: "591" },
  { name: "Bosnia and Herzegovina", nameId: "Bosnia dan Herzegovina", iso2: "BA", dialCode: "387" },
  { name: "Botswana", nameId: "Botswana", iso2: "BW", dialCode: "267" },
  { name: "Brazil", nameId: "Brasil", iso2: "BR", dialCode: "55" },
  { name: "British Indian Ocean Territory", nameId: "Wilayah Samudra Hindia Britania", iso2: "IO", dialCode: "246" },
  { name: "Brunei Darussalam", nameId: "Brunei Darussalam", iso2: "BN", dialCode: "673" },
  { name: "Bulgaria", nameId: "Bulgaria", iso2: "BG", dialCode: "359" },
  { name: "Burkina Faso", nameId: "Burkina Faso", iso2: "BF", dialCode: "226" },
  { name: "Burundi", nameId: "Burundi", iso2: "BI", dialCode: "257" },
  { name: "Cambodia", nameId: "Kamboja", iso2: "KH", dialCode: "855" },
  { name: "Cameroon", nameId: "Kamerun", iso2: "CM", dialCode: "237" },
  { name: "Canada", nameId: "Kanada", iso2: "CA", dialCode: "1" },
  { name: "Cape Verde", nameId: "Tanjung Verde", iso2: "CV", dialCode: "238" },
  { name: "Cayman Islands", nameId: "Kepulauan Cayman", iso2: "KY", dialCode: "1345" },
  { name: "Central African Republic", nameId: "Republik Afrika Tengah", iso2: "CF", dialCode: "236" },
  { name: "Chad", nameId: "Chad", iso2: "TD", dialCode: "235" },
  { name: "Chile", nameId: "Chili", iso2: "CL", dialCode: "56" },
  { name: "China", nameId: "Tiongkok", iso2: "CN", dialCode: "86" },
  { name: "Colombia", nameId: "Kolombia", iso2: "CO", dialCode: "57" },
  { name: "Comoros", nameId: "Komoro", iso2: "KM", dialCode: "269" },
  { name: "Congo", nameId: "Kongo", iso2: "CG", dialCode: "242" },
  { name: "Congo, Democratic Republic", nameId: "Kongo, Republik Demokratik", iso2: "CD", dialCode: "243" },
  { name: "Cook Islands", nameId: "Kepulauan Cook", iso2: "CK", dialCode: "682" },
  { name: "Costa Rica", nameId: "Kosta Rika", iso2: "CR", dialCode: "506" },
  { name: "Croatia", nameId: "Kroasia", iso2: "HR", dialCode: "385" },
  { name: "Cuba", nameId: "Kuba", iso2: "CU", dialCode: "53" },
  { name: "Curaçao", nameId: "Curaçao", iso2: "CW", dialCode: "599" },
  { name: "Cyprus", nameId: "Siprus", iso2: "CY", dialCode: "357" },
  { name: "Czech Republic", nameId: "Republik Ceko", iso2: "CZ", dialCode: "420" },
  { name: "Denmark", nameId: "Denmark", iso2: "DK", dialCode: "45" },
  { name: "Djibouti", nameId: "Djibouti", iso2: "DJ", dialCode: "253" },
  { name: "Dominica", nameId: "Dominika", iso2: "DM", dialCode: "1767" },
  { name: "Dominican Republic", nameId: "Republik Dominika", iso2: "DO", dialCode: "1809" },
  { name: "Ecuador", nameId: "Ekuador", iso2: "EC", dialCode: "593" },
  { name: "Egypt", nameId: "Mesir", iso2: "EG", dialCode: "20" },
  { name: "El Salvador", nameId: "El Salvador", iso2: "SV", dialCode: "503" },
  { name: "Equatorial Guinea", nameId: "Guinea Khatulistiwa", iso2: "GQ", dialCode: "240" },
  { name: "Eritrea", nameId: "Eritrea", iso2: "ER", dialCode: "291" },
  { name: "Estonia", nameId: "Estonia", iso2: "EE", dialCode: "372" },
  { name: "Eswatini", nameId: "Eswatini", iso2: "SZ", dialCode: "268" },
  { name: "Ethiopia", nameId: "Ethiopia", iso2: "ET", dialCode: "251" },
  { name: "Falkland Islands", nameId: "Kepulauan Falkland", iso2: "FK", dialCode: "500" },
  { name: "Faroe Islands", nameId: "Kepulauan Faroe", iso2: "FO", dialCode: "298" },
  { name: "Fiji", nameId: "Fiji", iso2: "FJ", dialCode: "679" },
  { name: "Finland", nameId: "Finlandia", iso2: "FI", dialCode: "358" },
  { name: "France", nameId: "Prancis", iso2: "FR", dialCode: "33" },
  { name: "French Guiana", nameId: "Guyana Prancis", iso2: "GF", dialCode: "594" },
  { name: "French Polynesia", nameId: "Polinesia Prancis", iso2: "PF", dialCode: "689" },
  { name: "Gabon", nameId: "Gabon", iso2: "GA", dialCode: "241" },
  { name: "Gambia", nameId: "Gambia", iso2: "GM", dialCode: "220" },
  { name: "Georgia", nameId: "Georgia", iso2: "GE", dialCode: "995" },
  { name: "Germany", nameId: "Jerman", iso2: "DE", dialCode: "49" },
  { name: "Ghana", nameId: "Ghana", iso2: "GH", dialCode: "233" },
  { name: "Gibraltar", nameId: "Gibraltar", iso2: "GI", dialCode: "350" },
  { name: "Greece", nameId: "Yunani", iso2: "GR", dialCode: "30" },
  { name: "Greenland", nameId: "Greenland", iso2: "GL", dialCode: "299" },
  { name: "Grenada", nameId: "Grenada", iso2: "GD", dialCode: "1473" },
  { name: "Guadeloupe", nameId: "Guadeloupe", iso2: "GP", dialCode: "590" },
  { name: "Guam", nameId: "Guam", iso2: "GU", dialCode: "1671" },
  { name: "Guatemala", nameId: "Guatemala", iso2: "GT", dialCode: "502" },
  { name: "Guinea", nameId: "Guinea", iso2: "GN", dialCode: "224" },
  { name: "Guinea-Bissau", nameId: "Guinea-Bissau", iso2: "GW", dialCode: "245" },
  { name: "Guyana", nameId: "Guyana", iso2: "GY", dialCode: "592" },
  { name: "Haiti", nameId: "Haiti", iso2: "HT", dialCode: "509" },
  { name: "Honduras", nameId: "Honduras", iso2: "HN", dialCode: "504" },
  { name: "Hong Kong", nameId: "Hong Kong", iso2: "HK", dialCode: "852" },
  { name: "Hungary", nameId: "Hungaria", iso2: "HU", dialCode: "36" },
  { name: "Iceland", nameId: "Islandia", iso2: "IS", dialCode: "354" },
  { name: "India", nameId: "India", iso2: "IN", dialCode: "91" },
  { name: "Indonesia", nameId: "Indonesia", iso2: "ID", dialCode: "62" },
  { name: "Iran", nameId: "Iran", iso2: "IR", dialCode: "98" },
  { name: "Iraq", nameId: "Irak", iso2: "IQ", dialCode: "964" },
  { name: "Ireland", nameId: "Irlandia", iso2: "IE", dialCode: "353" },
  { name: "Israel", nameId: "Israel", iso2: "IL", dialCode: "972" },
  { name: "Italy", nameId: "Italia", iso2: "IT", dialCode: "39" },
  { name: "Ivory Coast", nameId: "Pantai Gading", iso2: "CI", dialCode: "225" },
  { name: "Jamaica", nameId: "Jamaika", iso2: "JM", dialCode: "1876" },
  { name: "Japan", nameId: "Jepang", iso2: "JP", dialCode: "81" },
  { name: "Jordan", nameId: "Yordania", iso2: "JO", dialCode: "962" },
  { name: "Kazakhstan", nameId: "Kazakhstan", iso2: "KZ", dialCode: "7" },
  { name: "Kenya", nameId: "Kenya", iso2: "KE", dialCode: "254" },
  { name: "Kiribati", nameId: "Kiribati", iso2: "KI", dialCode: "686" },
  { name: "Kosovo", nameId: "Kosovo", iso2: "XK", dialCode: "383" },
  { name: "Kuwait", nameId: "Kuwait", iso2: "KW", dialCode: "965" },
  { name: "Kyrgyzstan", nameId: "Kirgizstan", iso2: "KG", dialCode: "996" },
  { name: "Laos", nameId: "Laos", iso2: "LA", dialCode: "856" },
  { name: "Latvia", nameId: "Latvia", iso2: "LV", dialCode: "371" },
  { name: "Lebanon", nameId: "Lebanon", iso2: "LB", dialCode: "961" },
  { name: "Lesotho", nameId: "Lesotho", iso2: "LS", dialCode: "266" },
  { name: "Liberia", nameId: "Liberia", iso2: "LR", dialCode: "231" },
  { name: "Libya", nameId: "Libya", iso2: "LY", dialCode: "218" },
  { name: "Liechtenstein", nameId: "Liechtenstein", iso2: "LI", dialCode: "423" },
  { name: "Lithuania", nameId: "Lithuania", iso2: "LT", dialCode: "370" },
  { name: "Luxembourg", nameId: "Luksemburg", iso2: "LU", dialCode: "352" },
  { name: "Macao", nameId: "Makau", iso2: "MO", dialCode: "853" },
  { name: "Madagascar", nameId: "Madagaskar", iso2: "MG", dialCode: "261" },
  { name: "Malawi", nameId: "Malawi", iso2: "MW", dialCode: "265" },
  { name: "Malaysia", nameId: "Malaysia", iso2: "MY", dialCode: "60" },
  { name: "Maldives", nameId: "Maladewa", iso2: "MV", dialCode: "960" },
  { name: "Mali", nameId: "Mali", iso2: "ML", dialCode: "223" },
  { name: "Malta", nameId: "Malta", iso2: "MT", dialCode: "356" },
  { name: "Marshall Islands", nameId: "Kepulauan Marshall", iso2: "MH", dialCode: "692" },
  { name: "Martinique", nameId: "Martinique", iso2: "MQ", dialCode: "596" },
  { name: "Mauritania", nameId: "Mauritania", iso2: "MR", dialCode: "222" },
  { name: "Mauritius", nameId: "Mauritius", iso2: "MU", dialCode: "230" },
  { name: "Mexico", nameId: "Meksiko", iso2: "MX", dialCode: "52" },
  { name: "Micronesia", nameId: "Mikronesia", iso2: "FM", dialCode: "691" },
  { name: "Moldova", nameId: "Moldova", iso2: "MD", dialCode: "373" },
  { name: "Monaco", nameId: "Monako", iso2: "MC", dialCode: "377" },
  { name: "Mongolia", nameId: "Mongolia", iso2: "MN", dialCode: "976" },
  { name: "Montenegro", nameId: "Montenegro", iso2: "ME", dialCode: "382" },
  { name: "Montserrat", nameId: "Montserrat", iso2: "MS", dialCode: "1664" },
  { name: "Morocco", nameId: "Maroko", iso2: "MA", dialCode: "212" },
  { name: "Mozambique", nameId: "Mozambik", iso2: "MZ", dialCode: "258" },
  { name: "Myanmar", nameId: "Myanmar", iso2: "MM", dialCode: "95" },
  { name: "Namibia", nameId: "Namibia", iso2: "NA", dialCode: "264" },
  { name: "Nauru", nameId: "Nauru", iso2: "NR", dialCode: "674" },
  { name: "Nepal", nameId: "Nepal", iso2: "NP", dialCode: "977" },
  { name: "Netherlands", nameId: "Belanda", iso2: "NL", dialCode: "31" },
  { name: "New Caledonia", nameId: "Kaledonia Baru", iso2: "NC", dialCode: "687" },
  { name: "New Zealand", nameId: "Selandia Baru", iso2: "NZ", dialCode: "64" },
  { name: "Nicaragua", nameId: "Nikaragua", iso2: "NI", dialCode: "505" },
  { name: "Niger", nameId: "Niger", iso2: "NE", dialCode: "227" },
  { name: "Nigeria", nameId: "Nigeria", iso2: "NG", dialCode: "234" },
  { name: "North Korea", nameId: "Korea Utara", iso2: "KP", dialCode: "850" },
  { name: "North Macedonia", nameId: "Makedonia Utara", iso2: "MK", dialCode: "389" },
  { name: "Norway", nameId: "Norwegia", iso2: "NO", dialCode: "47" },
  { name: "Oman", nameId: "Oman", iso2: "OM", dialCode: "968" },
  { name: "Pakistan", nameId: "Pakistan", iso2: "PK", dialCode: "92" },
  { name: "Palau", nameId: "Palau", iso2: "PW", dialCode: "680" },
  { name: "Palestine", nameId: "Palestina", iso2: "PS", dialCode: "970" },
  { name: "Panama", nameId: "Panama", iso2: "PA", dialCode: "507" },
  { name: "Papua New Guinea", nameId: "Papua Nugini", iso2: "PG", dialCode: "675" },
  { name: "Paraguay", nameId: "Paraguay", iso2: "PY", dialCode: "595" },
  { name: "Peru", nameId: "Peru", iso2: "PE", dialCode: "51" },
  { name: "Philippines", nameId: "Filipina", iso2: "PH", dialCode: "63" },
  { name: "Poland", nameId: "Polandia", iso2: "PL", dialCode: "48" },
  { name: "Portugal", nameId: "Portugal", iso2: "PT", dialCode: "351" },
  { name: "Puerto Rico", nameId: "Puerto Riko", iso2: "PR", dialCode: "1787" },
  { name: "Qatar", nameId: "Qatar", iso2: "QA", dialCode: "974" },
  { name: "Réunion", nameId: "Réunion", iso2: "RE", dialCode: "262" },
  { name: "Romania", nameId: "Rumania", iso2: "RO", dialCode: "40" },
  { name: "Russia", nameId: "Rusia", iso2: "RU", dialCode: "7" },
  { name: "Rwanda", nameId: "Rwanda", iso2: "RW", dialCode: "250" },
  { name: "Saint Kitts and Nevis", nameId: "Saint Kitts dan Nevis", iso2: "KN", dialCode: "1869" },
  { name: "Saint Lucia", nameId: "Saint Lucia", iso2: "LC", dialCode: "1758" },
  { name: "Saint Vincent and the Grenadines", nameId: "Saint Vincent dan Grenadines", iso2: "VC", dialCode: "1784" },
  { name: "Samoa", nameId: "Samoa", iso2: "WS", dialCode: "685" },
  { name: "San Marino", nameId: "San Marino", iso2: "SM", dialCode: "378" },
  { name: "São Tomé and Príncipe", nameId: "São Tomé dan Príncipe", iso2: "ST", dialCode: "239" },
  { name: "Saudi Arabia", nameId: "Arab Saudi", iso2: "SA", dialCode: "966" },
  { name: "Senegal", nameId: "Senegal", iso2: "SN", dialCode: "221" },
  { name: "Serbia", nameId: "Serbia", iso2: "RS", dialCode: "381" },
  { name: "Seychelles", nameId: "Seychelles", iso2: "SC", dialCode: "248" },
  { name: "Sierra Leone", nameId: "Sierra Leone", iso2: "SL", dialCode: "232" },
  { name: "Singapore", nameId: "Singapura", iso2: "SG", dialCode: "65" },
  { name: "Slovakia", nameId: "Slovakia", iso2: "SK", dialCode: "421" },
  { name: "Slovenia", nameId: "Slovenia", iso2: "SI", dialCode: "386" },
  { name: "Solomon Islands", nameId: "Kepulauan Solomon", iso2: "SB", dialCode: "677" },
  { name: "Somalia", nameId: "Somalia", iso2: "SO", dialCode: "252" },
  { name: "South Africa", nameId: "Afrika Selatan", iso2: "ZA", dialCode: "27" },
  { name: "South Korea", nameId: "Korea Selatan", iso2: "KR", dialCode: "82" },
  { name: "South Sudan", nameId: "Sudan Selatan", iso2: "SS", dialCode: "211" },
  { name: "Spain", nameId: "Spanyol", iso2: "ES", dialCode: "34" },
  { name: "Sri Lanka", nameId: "Sri Lanka", iso2: "LK", dialCode: "94" },
  { name: "Sudan", nameId: "Sudan", iso2: "SD", dialCode: "249" },
  { name: "Suriname", nameId: "Suriname", iso2: "SR", dialCode: "597" },
  { name: "Sweden", nameId: "Swedia", iso2: "SE", dialCode: "46" },
  { name: "Switzerland", nameId: "Swiss", iso2: "CH", dialCode: "41" },
  { name: "Syria", nameId: "Suriah", iso2: "SY", dialCode: "963" },
  { name: "Taiwan", nameId: "Taiwan", iso2: "TW", dialCode: "886" },
  { name: "Tajikistan", nameId: "Tajikistan", iso2: "TJ", dialCode: "992" },
  { name: "Tanzania", nameId: "Tanzania", iso2: "TZ", dialCode: "255" },
  { name: "Thailand", nameId: "Thailand", iso2: "TH", dialCode: "66" },
  { name: "Timor-Leste", nameId: "Timor Leste", iso2: "TL", dialCode: "670" },
  { name: "Togo", nameId: "Togo", iso2: "TG", dialCode: "228" },
  { name: "Tonga", nameId: "Tonga", iso2: "TO", dialCode: "676" },
  { name: "Trinidad and Tobago", nameId: "Trinidad dan Tobago", iso2: "TT", dialCode: "1868" },
  { name: "Tunisia", nameId: "Tunisia", iso2: "TN", dialCode: "216" },
  { name: "Turkey", nameId: "Turki", iso2: "TR", dialCode: "90" },
  { name: "Turkmenistan", nameId: "Turkmenistan", iso2: "TM", dialCode: "993" },
  { name: "Turks and Caicos Islands", nameId: "Kepulauan Turks dan Caicos", iso2: "TC", dialCode: "1649" },
  { name: "Tuvalu", nameId: "Tuvalu", iso2: "TV", dialCode: "688" },
  { name: "Uganda", nameId: "Uganda", iso2: "UG", dialCode: "256" },
  { name: "Ukraine", nameId: "Ukraina", iso2: "UA", dialCode: "380" },
  { name: "United Arab Emirates", nameId: "Uni Emirat Arab", iso2: "AE", dialCode: "971" },
  { name: "United Kingdom", nameId: "Britania Raya", iso2: "GB", dialCode: "44" },
  { name: "United States", nameId: "Amerika Serikat", iso2: "US", dialCode: "1" },
  { name: "Uruguay", nameId: "Uruguay", iso2: "UY", dialCode: "598" },
  { name: "Uzbekistan", nameId: "Uzbekistan", iso2: "UZ", dialCode: "998" },
  { name: "Vanuatu", nameId: "Vanuatu", iso2: "VU", dialCode: "678" },
  { name: "Vatican City", nameId: "Vatikan", iso2: "VA", dialCode: "379" },
  { name: "Venezuela", nameId: "Venezuela", iso2: "VE", dialCode: "58" },
  { name: "Vietnam", nameId: "Vietnam", iso2: "VN", dialCode: "84" },
  { name: "Virgin Islands (British)", nameId: "Kepulauan Virgin (Britania)", iso2: "VG", dialCode: "1284" },
  { name: "Virgin Islands (US)", nameId: "Kepulauan Virgin (AS)", iso2: "VI", dialCode: "1340" },
  { name: "Yemen", nameId: "Yaman", iso2: "YE", dialCode: "967" },
  { name: "Zambia", nameId: "Zambia", iso2: "ZM", dialCode: "260" },
  { name: "Zimbabwe", nameId: "Zimbabwe", iso2: "ZW", dialCode: "263" },
];

function findCountryByIso2(iso2) {
  return countries.find(function (c) { return c.iso2 === iso2; });
}

var DEFAULT_COUNTRY_ISO2 = "ID";
